# Media configuration for file uploads
media:
  input: content/static
  output: /static

# Content collections - organized for stream of consciousness and link-blogging
content:
  # 📎 Gaggle of Links - Interesting stuff you stumble upon on the internet
  - name: gaggle-of-links
    label: 📎 Gaggle of Links
    type: collection
    path: content/gaggle-of-links
    view: 
      fields: [title, date, url]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: url
        label: Link URL
        type: string
      - name: source
        label: Source
        type: string
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "tech", "design", "productivity", "random", "interesting" ]
      - name: archive
        label: Archive this
        type: boolean
        default: false
      - name: description
        label: Description
        type: text
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Your thoughts
        type: rich-text
        required: true

  # 💭 Brain Dumps - Stream of consciousness, fleeting observations
  - name: brain-dumps
    label: 💭 Brain Dumps
    type: collection
    path: content/brain-dumps
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: mood
        label: Mood/Context
        type: select
        options:
          values: [ "curious", "frustrated", "excited", "contemplative", "random", "nostalgic" ]
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "thoughts", "ideas", "personal", "random" ]
      - name: draft
        label: Keep private
        type: boolean
        default: false
      - name: description
        label: Description
        type: text
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Stream of consciousness
        type: rich-text
        required: true

  # 📝 Stolen Wisdom - Insights pilfered from things you consume
  - name: stolen-wisdom
    label: 📝 Stolen Wisdom
    type: collection
    path: content/stolen-wisdom
    view:
      fields: [title, date, source_type]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: source_author
        label: Author/Creator
        type: string
      - name: source_type
        label: Content Type
        type: select
        options:
          values: [ "book", "article", "video", "podcast", "documentary", "course", "conversation" ]
        required: true
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "learning", "insights", "wisdom", "books", "articles" ]
      - name: rating
        label: Your Rating
        type: select
        options:
          values: [ "⭐", "⭐⭐", "⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐⭐⭐" ]
      - name: description
        label: Description
        type: text
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Key takeaways & thoughts
        type: rich-text
        required: true

  # 🕳️ Link Blackhole - Where bookmarks and good intentions disappear forever
  - name: link-blackhole
    label: 🕳️ Link Blackhole
    type: collection
    path: content/link-blackhole
    view:
      fields: [title, date, status]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: url
        label: URL
        type: string
        required: true
      - name: source
        label: Source
        type: string
      - name: status
        label: Status
        type: select
        options:
          values: [ "to-read", "reading", "read", "archived" ]
        default: "to-read"
        required: true
      - name: priority
        label: Priority
        type: select
        options:
          values: [ "low", "medium", "high" ]
        default: "medium"
      - name: estimated_time
        label: Est. Reading Time
        type: string
      - name: date_added
        label: Date Added
        type: date
        default: now
      - name: date_read
        label: Date Read
        type: date
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "articles", "books", "learning", "later" ]
      - name: description
        label: Description
        type: text
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Notes & Summary
        type: rich-text

  # 🤖 Bot Brainstorms - Learning adventures with AI companions
  - name: machine-taught
    label: 🤖 Machine-Taught
    type: collection
    path: content/machine-taught
    view:
      fields: [title, date, topic]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: topic
        label: Learning Topic
        type: string
        required: true
      - name: ai_partner
        label: AI Partner
        type: select
        options:
          values: [ "Claude", "ChatGPT", "Perplexity", "Gemini", "Other" ]
        default: "Claude"
      - name: date
        label: Date
        type: date
        default: now
        required: true
      - name: duration
        label: Session Duration
        type: string
      - name: difficulty
        label: Difficulty Level
        type: select
        options:
          values: [ "beginner", "intermediate", "advanced" ]
        default: "intermediate"
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "programming", "science", "philosophy", "history", "math", "creative", "business" ]
      - name: key_insights
        label: Key Insights
        type: text
      - name: description
        label: Description
        type: text
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Conversation Transcript
        type: rich-text
        required: true

  # ✍️ Proper Posts - When you actually try to write something coherent
  - name: proper-posts
    label: ✍️ Proper Posts
    type: collection
    path: content/proper-posts
    view: 
      fields: [title, date, status]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
      - name: description
        label: Description
        type: text
        required: true
      - name: date
        label: Date
        type: date
        default: now
      - name: status
        label: Status
        type: select
        options:
          values: [ "draft", "published", "archived" ]
        default: "draft"
        required: true
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [ "essay", "thoughts", "personal", "tech", "writing" ]
      - name: crosspost_substack
        label: Cross-post to Substack
        type: boolean
        default: false
      - name: image
        label: Social Image
        type: file
        directory: static/social
        public_path: /static/social
      - name: body
        label: Essay Content
        type: rich-text
        required: true

  # Single pages
  - name: pages
    label: Pages
    type: file
    path: content
    view:
      fields: [title]
    files:
      - name: about
        label: About Page
        file: about.md
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: body
            label: Content
            type: rich-text
            required: true
      - name: index
        label: Home Page
        file: index.md
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: body
            label: Content
            type: rich-text
            required: true

# Global settings
settings:
  title: Digital Garden CMS
  description: Content management for alittlelessdumb.pages.dev
  logo: /static/logo.png
