# Media configuration for file uploads
media:
  input: content/static
  output: /static

# Content collections - organized for stream of consciousness and link-blogging
content:
  # 📎 Gaggle of Links - Interesting stuff you stumble upon on the internet
  - name: gaggle-of-links
    label: 📎 Gaggle of Links
    type: collection
    path: content/gaggle-of-links
    view: 
      fields: [title, date, url]
    fields:
      - name: title
        label: Title
        type: string
        required: true
        hint: What caught your attention?
      - name: url
        label: Link URL
        type: string
        hint: The link you're saving (optional for non-link posts)
      - name: source
        label: Source
        type: string
        hint: Where you found this (Twitter, HN, Reddit, etc.)
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: list
        item_type: string
        hint: Topics, themes, or keywords
      - name: archive
        label: Archive this
        type: boolean
        default: false
        hint: Mark as archived to hide from main feed
      - name: body
        label: Your thoughts
        type: rich-text
        required: true
        hint: Why is this interesting? What does it make you think?
        options:
          media: default
          path: static
          extensions: [jpg, jpeg, png, gif, webp]

  # 💭 Brain Dumps - Stream of consciousness, fleeting observations
  - name: brain-dumps
    label: 💭 Brain Dumps
    type: collection
    path: content/brain-dumps
    view:
      fields: [title, date]
    fields:
      - name: title
        label: Title
        type: string
        required: true
        hint: What's on your mind?
      - name: mood
        label: Mood/Context
        type: select
        options:
          - { label: "Curious", value: "curious" }
          - { label: "Frustrated", value: "frustrated" }
          - { label: "Excited", value: "excited" }
          - { label: "Contemplative", value: "contemplative" }
          - { label: "Random", value: "random" }
          - { label: "Nostalgic", value: "nostalgic" }
        hint: What headspace are you in?
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: list
        item_type: string
        hint: Themes or topics
      - name: draft
        label: Keep private
        type: boolean
        default: false
        hint: Sometimes thoughts need to marinate
      - name: body
        label: Stream of consciousness
        type: rich-text
        required: true
        hint: Let it flow...
        options:
          media: default
          path: static
          extensions: [jpg, jpeg, png, gif, webp]

  # 📝 Stolen Wisdom - Insights pilfered from things you consume
  - name: stolen-wisdom
    label: 📝 Stolen Wisdom
    type: collection
    path: content/stolen-wisdom
    view:
      fields: [title, date, source_type]
    fields:
      - name: title
        label: Title
        type: string
        required: true
        hint: What did you learn?
      - name: source_title
        label: Source Title
        type: string
        required: true
        hint: Book/article/video/podcast title
      - name: source_author
        label: Author/Creator
        type: string
        hint: Who created this?
      - name: source_type
        label: Content Type
        type: select
        options:
          - { label: "Book", value: "book" }
          - { label: "Article", value: "article" }
          - { label: "Video", value: "video" }
          - { label: "Podcast", value: "podcast" }
          - { label: "Documentary", value: "documentary" }
          - { label: "Course", value: "course" }
          - { label: "Conversation", value: "conversation" }
        required: true
      - name: source_url
        label: Source Link
        type: string
        hint: Link to the original content
      - name: date
        label: Date
        type: date
        default: now
      - name: tags
        label: Tags
        type: list
        item_type: string
        hint: Key concepts or themes
      - name: rating
        label: Your Rating
        type: select
        options:
          - { label: "⭐ (1 star)", value: "⭐" }
          - { label: "⭐⭐ (2 stars)", value: "⭐⭐" }
          - { label: "⭐⭐⭐ (3 stars)", value: "⭐⭐⭐" }
          - { label: "⭐⭐⭐⭐ (4 stars)", value: "⭐⭐⭐⭐" }
          - { label: "⭐⭐⭐⭐⭐ (5 stars)", value: "⭐⭐⭐⭐⭐" }
        hint: How much did you enjoy/learn from this?
      - name: body
        label: Key takeaways & thoughts
        type: rich-text
        required: true
        hint: What resonated? What will you remember?
        options:
          media: default
          path: static
          extensions: [jpg, jpeg, png, gif, webp]

  # 📚 Someday Stack - Your personal pile of "I'll read this someday" links
  - name: someday-stack
    label: 📚 Someday Stack
    type: collection
    path: content/someday-stack
    view:
      fields: [title, date, status]
    fields:
      - name: title
        label: Title
        type: string
        required: true
        hint: Article/book/content title
      - name: url
        label: URL
        type: string
        required: true
        hint: Link to save for later
      - name: source
        label: Source
        type: string
        hint: Website, author, or where you found it
      - name: status
        label: Status
        type: select
        options:
          - { label: "To Read", value: "to-read" }
          - { label: "Currently Reading", value: "reading" }
          - { label: "Read", value: "read" }
          - { label: "Archived", value: "archived" }
        default: "to-read"
        required: true
      - name: priority
        label: Priority
        type: select
        options:
          - { label: "Low", value: "low" }
          - { label: "Medium", value: "medium" }
          - { label: "High", value: "high" }
        default: "medium"
      - name: estimated_time
        label: Est. Reading Time
        type: string
        hint: "5 min read, 2 hours, etc."
      - name: date_added
        label: Date Added
        type: date
        default: now
      - name: date_read
        label: Date Read
        type: date
        hint: When you actually read it
      - name: tags
        label: Tags
        type: list
        item_type: string
        hint: Topics or categories
      - name: body
        label: Notes & Summary
        type: rich-text
        hint: Why you saved it, key points after reading
        options:
          media: default
          path: static
          extensions: [jpg, jpeg, png, gif, webp]

  # ✍️ Proper Posts - When you actually try to write something coherent
  - name: proper-posts
    label: ✍️ Proper Posts
    type: collection
    path: content/proper-posts
    view: 
      fields: [title, date, status]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
        hint: Optional subtitle or tagline
      - name: description
        label: Description
        type: text
        required: true
        hint: What's this essay about? (for SEO and previews)
      - name: date
        label: Date
        type: date
        default: now
      - name: status
        label: Status
        type: select
        options:
          - { label: "Draft", value: "draft" }
          - { label: "Published", value: "published" }
          - { label: "Archived", value: "archived" }
        default: "draft"
        required: true
      - name: tags
        label: Tags
        type: list
        item_type: string
        hint: Main themes and topics
      - name: crosspost_substack
        label: Cross-post to Substack
        type: boolean
        default: false
        hint: Will you share this on your newsletter?
      - name: body
        label: Essay Content
        type: rich-text
        required: true
        options:
          media: default
          path: static
          extensions: [jpg, jpeg, png, gif, webp]

  # Single pages
  - name: pages
    label: Pages
    type: file
    path: content
    view:
      fields: [title]
    files:
      - name: about
        label: About Page
        file: about.md
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: body
            label: Content
            type: rich-text
            required: true
            options:
              media: default
              path: static
              extensions: [jpg, jpeg, png, gif, webp]
      - name: index
        label: Home Page
        file: index.md
        fields:
          - name: title
            label: Title
            type: string
            required: true
          - name: body
            label: Content
            type: rich-text
            required: true
            options:
              media: default
              path: static
              extensions: [jpg, jpeg, png, gif, webp]

# Global settings
settings:
  title: Digital Garden CMS
  description: Content management for alittlelessdumb.pages.dev
  logo: /static/logo.png
