base_url = "https://alittlelessdumb.pages.dev"
title = "A Little Less Dumb"
theme = "anemone"

# Then the rest of your configuration...
[extra]
author = "Bhuvanesh"
display_author = true
list_pages = true

# Navigation
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about", name_en = "/about/" },
  { url = "/journal", name_en = "/journal/" },
  { url = "/blog", name_en = "/blog/" }
]

# Status update
latest_text = "Setting up my personal website with Zola"

# Your links
links = [
    { name = "Email", url = "mailto:your@email.com" },
    { name = "GitHub", url = "https://github.com/bebhuvan" }
]
