# Basic site config
base_url = "https://alittlelessdumb.pages.dev"
title = "A Little Less Dumb"
theme = "anemone"

# Theme requirements
compile_sass = true
build_search_index = true
generate_feed = true

# Syntax highlighting
[markdown]
highlight_code = true

# Theme customization
[extra]
# Display a list of posts on the homepage
list_pages = true
# You can customize this later
twitter_card = false
