# For local testing - uncomment the test-repo backend below
backend:
  name: test-repo

# For production - replace with your actual GitHub repo
# backend:
#   name: github
#   repo: your-username/your-repo  # TODO: replace with your GitHub username/repository-name
#   branch: main
#   # For GitHub backend, you need to set up OAuth:
#   # 1. Go to https://github.com/settings/developers
#   # 2. Create a new OAuth App
#   # 3. Use your Netlify/Vercel URL for production

media_folder: "content/images"  # Where to store uploaded images
public_folder: "/images"  # Public URL path for images

# Remove auth_endpoint - it's not needed for standard GitHub backend
# If you want to test locally, use:
# backend:
#   name: test-repo

collections:
  - name: "linklitter"
    label: "Link-Litter"
    folder: "content/link-litter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "minimusings"
    label: "Mini Musings"
    folder: "content/mini-musings"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tinysparks"
    label: "Tiny Sparks"
    folder: "content/tiny-sparks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
